resolver: lts-14.6
packages:
- .
- ../pandoc

flags:
  pandoc:
    embed_data_files: true

# extra-deps:
# - pandoc-citeproc-0.14.1.5
# - hslua-0.9.5
# - skylighting-0.6
# - ansi-terminal-0.7.1.1
# - tasty-1.0.0.1
# - texmath-0.10.1.1
# - tagsoup-0.14.6

extra-deps:
- git: https://github.com/jgm/citeproc
  commit: 342a1d3bc2fcd5b4a1586962aedada5f31db606a
- pandoc-types-1.22
- texmath-0.12.0.3
- rfc5051-0.2
- haddock-library-1.9.0
- skylighting-0.10.0.2
- skylighting-core-0.10.0.2
- doclayout-0.3
- emojis-0.1
- hslua-1.1.2
- jira-wiki-markup-1.3.2
- HsYAML-0.2.1.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.8.2
- commonmark-0.1.0.2
- commonmark-extensions-0.2.0.1
- commonmark-pandoc-0.2.0.1

